version "4.6.0"

#include "zscript/health.zs"
#include "zscript/herbs.zs"
#include "zscript/hud.zs"
#include "zscript/player.zs"
#include "zscript/armor.zs"
#include "zscript/weapons/base.zs"
#include "zscript/weapons/fist.zs"
#include "zscript/weapons/pistol.zs"
#include "zscript/weapons/smg.zs"
#include "zscript/weapons/shotgun.zs"
#include "zscript/weapons/launcher.zs"
#include "zscript/weapons/cannon.zs"
#include "zscript/weapons/thunder.zs"
#include "zscript/weapons/laz.zs"